org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[1,)

mod_id=craft_notify
mod_name=Craft Notify
mod_license=MIT
mod_version=0.6.0
mod_group_id=dev.thou.craftnotify

forge_minecraft_version=1.20.1
forge_minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_loader_version_range=[47,)
forge_parchment_minecraft_version=1.20.1
forge_parchment_mappings_version=2023.09.03
